spring:
  datasource:
    password: Admin@123
    url: jdbc:mysql://localhost:3306/oauth_login
    username: dev
  jpa:
    hibernate:
      ddl-auto: create

  security:
    oauth2:
      client:
        registration:
         google:
          clientId: 981808715825-eoip6q3ugp050q4o4j4gmatrajaacgl9.apps.googleusercontent.com
          clientSecret: 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
          scope:
           - email
           - profile
